// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"UR65_SmartPhoneUI","status":true,"description":"スマホ用UI  ver 1.0.0\nUIのサイズをスマートフォン向けに最適化します。","parameters":{"タイトル":"1","メニュー":"1","アイテム":"1","スキル":"1","装備":"1","オプション":"1","ゲーム終了":"1","戦闘":"1","ショップ":"1","イベント関係":"1","アイコン位置修正":"1"}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン","parameters":{}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{}},
{"name":"TMMapHpGauge","status":true,"description":"マップシーンに顔グラフィックとＨＰゲージを表示します。\n必要に応じてＭＰや変数などをゲージで表示することもできます。","parameters":{"gaugeWindowX":"0","gaugeWindowY":"0","gaugeWindowWidth":"817","gaugeWindowHeight":"100","gaugeAType":"HP","gaugeAX":"377","gaugeAY":"12","gaugeAWidth":"300","gaugeAHeight":"36","gaugeAFontSize":"28","gaugeAParam":"0","gaugeAMax":"0","gaugeAName":"AP","gaugeAColor":"#ff60c0 #ffa0e0","gaugeBType":"MP","gaugeBX":"377","gaugeBY":"50","gaugeBWidth":"300","gaugeBHeight":"36","gaugeBFontSize":"28","gaugeBParam":"0","gaugeBMax":"0","gaugeBName":"BP","gaugeBColor":"#ff60c0 #ffa0e0","gaugeCType":"VN","gaugeCX":"30","gaugeCY":"32","gaugeCWidth":"300","gaugeCHeight":"36","gaugeCFontSize":"28","gaugeCParam":"12","gaugeCMax":"11","gaugeCName":"敵HP","gaugeCColor":"#ff60c0 #ffa0e0","faceOffsetX":"-4","faceOffsetY":"-4","stateIconMax":"0","stateIconX":"156","stateIconY":"24","goldWidth":"0","goldX":"12","goldY":"12","shakeTime":"40","startVisible":"1","windowOpacity":"255","collideOpacity":"128","messageBusyHide":"0","eventBusyHide":"0"}}
];
